# Generated by Django 5.0.7 on 2024-08-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50, verbose_name='Нзвание поста')),
                ('publication_text', models.TextField()),
                ('author_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
