# Generated by Django 5.0.7 on 2024-08-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_user',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AddField(
            model_name='blog_user',
            name='image_post',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото публикации'),
        ),
        migrations.AlterField(
            model_name='blog_user',
            name='publication_text',
            field=models.TextField(verbose_name='Текст публикации'),
        ),
    ]
