# Generated by Django 5.0.7 on 2024-08-22 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_user_options_blog_user_image_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_user',
            name='image_post',
            field=models.ImageField(default=1, upload_to='image%Y', verbose_name='Фото публикации'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('text_comment', models.TextField(max_length=600)),
                ('to_which_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog_user', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
    ]
